name: Release packages

on:
   push:
      branches:
         - main
      tags:
         - v*
   
jobs:
   build:
      name: Release packages
      runs-on: windows-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: "8.0.x"

         - name: 'Install Latest .NET MAUI Workload'
           run: dotnet workload install maui

         - name: Install dependencies
           run: dotnet restore

         - name: Build
           run: dotnet build -c Release

         - name: Package
           run: dotnet pack -c Release --no-build --output nupkgs

         - name: Publish
           run: dotnet nuget push nupkgs/ -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} 